# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-06-04 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_auto_20200925_2219'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False, verbose_name='\u7f16\u53f7')),
                ('username', models.CharField(max_length=20, unique=True, verbose_name='\u7528\u6237\u540d')),
                ('password', models.CharField(max_length=32, verbose_name='\u5bc6\u7801')),
                ('tel', models.CharField(max_length=20, verbose_name='\u624b\u673a\u53f7')),
                ('reg_date', models.DateTimeField(auto_now_add=True, verbose_name='\u6ce8\u518c\u65f6\u95f4')),
                ('last_visit', models.DateTimeField(null=True, verbose_name='\u6700\u540e\u767b\u5f55\u65f6\u95f4')),
            ],
            options={
                'db_table': 'tb_user',
                'verbose_name': '\u7528\u6237',
                'verbose_name_plural': '\u7528\u6237',
            },
        ),
    ]
