# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-06-05 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmsg',
            name='read',
            field=models.IntegerField(default=0, verbose_name='\u9605\u8bfb\u91cf'),
        ),
    ]
