# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-06-05 14:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_blogmsg_read'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogmsg',
            name='read',
        ),
    ]
