# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-09-25 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmsg',
            name='date',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='\u6587\u7ae0\u521b\u5efa\u65f6\u95f4'),
        ),
    ]
